/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bigbrew_pos;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author JOIBOI
 */
public class mainPOS extends javax.swing.JFrame {

    /**
     * Creates new form mainPOS
     */
    public mainPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanelPOS = new javax.swing.JPanel();
        maintopBorder = new javax.swing.JPanel();
        logoutBttn = new javax.swing.JButton();
        topTitle = new javax.swing.JLabel();
        mainbottomBorder = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Point of Sale - BigBrew Coffee Shop");

        mainPanelPOS.setBackground(new java.awt.Color(240, 215, 188));

        javax.swing.GroupLayout mainPanelPOSLayout = new javax.swing.GroupLayout(mainPanelPOS);
        mainPanelPOS.setLayout(mainPanelPOSLayout);
        mainPanelPOSLayout.setHorizontalGroup(
            mainPanelPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1292, Short.MAX_VALUE)
        );
        mainPanelPOSLayout.setVerticalGroup(
            mainPanelPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );

        maintopBorder.setBackground(new java.awt.Color(187, 111, 27));

        logoutBttn.setBackground(new java.awt.Color(226, 92, 92));
        logoutBttn.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        logoutBttn.setText("Logout");
        logoutBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBttnActionPerformed(evt);
            }
        });

        topTitle.setBackground(new java.awt.Color(255, 255, 255));
        topTitle.setFont(new java.awt.Font("Roboto Bk", 0, 36)); // NOI18N
        topTitle.setForeground(new java.awt.Color(255, 255, 255));
        topTitle.setText("BIGBREW COFFEE SHOP");

        javax.swing.GroupLayout maintopBorderLayout = new javax.swing.GroupLayout(maintopBorder);
        maintopBorder.setLayout(maintopBorderLayout);
        maintopBorderLayout.setHorizontalGroup(
            maintopBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintopBorderLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(logoutBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233)
                .addComponent(topTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        maintopBorderLayout.setVerticalGroup(
            maintopBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maintopBorderLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(maintopBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(topTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutBttn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        mainbottomBorder.setBackground(new java.awt.Color(25, 25, 25));

        javax.swing.GroupLayout mainbottomBorderLayout = new javax.swing.GroupLayout(mainbottomBorder);
        mainbottomBorder.setLayout(mainbottomBorderLayout);
        mainbottomBorderLayout.setHorizontalGroup(
            mainbottomBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainbottomBorderLayout.setVerticalGroup(
            mainbottomBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(maintopBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainbottomBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanelPOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(maintopBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanelPOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainbottomBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBttnActionPerformed
        // Opens the Option Pane to Confirm
        int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout this session?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        
        if (option == JOptionPane.YES_OPTION) {
        // Perform logout operation
        // TODO: Add your logout code here
        
        // This is to close the mainPOS window if the user pushes the button
        dispose();
        
        // This opens the userAuth if the user is out from the session
        java.awt.EventQueue.invokeLater(() -> {
            userAuth auth = new userAuth();

            // Center the userAuth frame on the screen
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            int screenWidth = screenSize.width;
            int screenHeight = screenSize.height;
            int frameWidth = auth.getWidth();
            int frameHeight = auth.getHeight();
            int x = (screenWidth - frameWidth) / 2;
            int y = (screenHeight - frameHeight) / 2;
            auth.setLocation(x, y);
            
            auth.setVisible(true);
        });
        } else {
        // User clicked Cancel, do nothing
        }
    }//GEN-LAST:event_logoutBttnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton logoutBttn;
    private javax.swing.JPanel mainPanelPOS;
    private javax.swing.JPanel mainbottomBorder;
    private javax.swing.JPanel maintopBorder;
    private javax.swing.JLabel topTitle;
    // End of variables declaration//GEN-END:variables
}
